default: &default
  adapter: 'mysql2'
  username: 'root'
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: backend_dev

test:
  <<: *default
  database: backend_test

staging:
  adapter: 'mysql2'
  database: <%= ENV['BACKEND_DB'] %>
  username: <%= ENV['BACKEND_DB_USER'] %>
  password: <%= ENV['BACKEND_DB_PASSWORD'] %>
  host: <%= ENV['BACKEND_DB_HOST'] %>
  pool: 5
  timeout: 5000
  reconnect: true

production:
  adapter: 'mysql2'
  database: <%= ENV['BACKEND_DB'] %>
  username: <%= ENV['BACKEND_DB_USER'] %>
  password: <%= ENV['BACKEND_DB_PASSWORD'] %>
  host: <%= ENV['BACKEND_DB_HOST'] %>
  pool: 10
  timeout: 5000
  reconnect: true
